# permissions to do viewer experiments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: experiment-viewer-role
rules:
- apiGroups:
  - iter8.iter8.tools
  resources:
  - experiments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - iter8.iter8.tools
  resources:
  - experiments/status
  verbs:
  - get
